### ISSUE TITLE
Immich Server won't start anymore

### ISSUE THREAD

**Issue by savisaar2** [immich-app/immich-charts#141]
So I had my cluster off for a little while, and when I started again and updated to the 0.8.4, v1.119.0 I am unable to get the server pod to run. A whole bunch of redis socket errors are in logs.

Is helm chat 0.8.4 broken?

**Comment by bo0tzz** [comment]
Not much to go off here, can you post the errors as well as other relevant info like your values.yaml?

**Comment by savisaar2** [comment]
Yeah I’m just going to gather that stuff. Just rolled back to an earlier
working version.

**Comment by prometheanfire** [comment]
The healthcheck is failing, I'm not able to see what port it's actually running on from within the container though.

```
│   Warning  Unhealthy  9m33s (x46 over 68m)   kubelet  Startup probe failed: Get "http://1.2.3.4:2283/api/server/ping": dial tcp 1.2.3.4:2283: connect: connection refused                                                           │
```

Here are logs from within the container
```
Initializing Immich v1.119.1
Detected CPU Cores: 12
Starting api worker
Starting microservices worker
[Nest] 6  - 10/31/2024, 12:19:16 AM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 6  - 10/31/2024, 12:19:16 AM     LOG [Microservices:MapRepository] Initializing metadata repository
[Nest] 16  - 10/31/2024, 12:19:17 AM     LOG [Api:EventRepository] Initialized websocket server
```
I'm going to try an uninstall and reinstall to see if that does anything

**Comment by prometheanfire** [comment]
no luck, not listening on 3001 or 2283

`for NS in $(ip netns ls | awk '{ print $1 }'); do ip netns exec $NS ss -lntp; done | grep 2283` returned nothing for both 2283 and 3001, I'll need to increase verbosity / debug.

**Comment by prometheanfire** [comment]
Ok, got it working, not sure if what I did last was the actual solution, but here it be.

I updated `postgresql.primary.resourcesPreset` to `micro` from the default of `nano`
https://github.com/bitnami/charts/blob/bd4b9b984d012a85471d654329cb0c16b5b0f062/bitnami/common/templates/_resources.tpl#L20

I'm sure it could use better tuning, and the upstream bitnami docs say not to use presets in production but to tune properly but... quick fix.

How I found it was taking from your (@bo0tzz's) comment https://github.com/immich-app/immich/discussions/13459#discussioncomment-10969642  could have been a deadlock as suggested as well since it'll restart the container when changing the resource limits.

**Comment by rmlamarche** [comment]
Thanks @prometheanfire ! I was just debugging this same issue (immich-server not starting, didn't seem to be listening on any port(s) in the pod), then I was watching events and seeing postgres go OOM and get killed by k8s. Increasing the resource limits in postgres did the trick for me, too, so that makes at least 2 of us

**Comment by savisaar2** [comment]
So for my setup I'm not using the inbuilt Postgres I have it connected to an external Postgres instance. I'm not too sure what is wrong with the setup it seems to run with 0.7.0, v1.110.0, but anything newer it fails.

**Comment by bo0tzz** [comment]
Please post the logs

**Comment by savisaar2** [comment]
Not sure if this helps but I am on my mobile so it's hard to capture the logs text but this is what the server is spitting out:

![image](https://github.com/user-attachments/assets/8dc853f9-2bef-4ccc-a574-d653aa8bf917)

Nothing else is giving me any valuable information.

Any suggestions of what other tests I can do I will do.

**Comment by bo0tzz** [comment]
You'll need to post the actual full logs as a text file, this isn't very useful. Also take a look at the redis pod, make sure it's running and post its logs.

**Comment by savisaar2** [comment]
Sure thing I’ll do that in the morning on the laptop. Hope I can eventually
find the fix for this, I enjoy it too much to lose it.

**Comment by savisaar2** [comment]
Logs from the server:

```

Initializing Immich v1.119.1

Detected CPU Cores: 4

Starting api worker

Starting microservices worker

[32m[Nest] 8  - [39m10/31/2024, 5:23:19 PM [32m    LOG[39m [33m[Microservices:EventRepository][39m [32mInitialized websocket server[39m

[32m[Nest] 18  - [39m10/31/2024, 5:23:20 PM [32m    LOG[39m [33m[Api:EventRepository][39m [32mInitialized websocket server[39m

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

missing 'error' handler on this Redis client

missing 'error' handler on this Redis client

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

Error: connect ETIMEDOUT

    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)

    at Object.onceWrapper (node:events:633:28)

    at Socket.emit (node:events:519:28)

    at Socket._onTimeout (node:net:591:8)

    at listOnTimeout (node:internal/timers:581:17)

    at process.processTimers (node:internal/timers:519:7) {

  errorno: 'ETIMEDOUT',

  code: 'ETIMEDOUT',

  syscall: 'connect'

}

missing 'error' handler on this Redis client

missing 'error' handler on this Redis client
```

Logs from redis:
```

1:C 31 Oct 2024 15:11:57.297 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

1:C 31 Oct 2024 15:11:57.297 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=1, just started

1:C 31 Oct 2024 15:11:57.297 * Configuration loaded

1:M 31 Oct 2024 15:11:57.298 * monotonic clock: POSIX clock_gettime

1:M 31 Oct 2024 15:11:57.299 * Running mode=standalone, port=6379.

1:M 31 Oct 2024 15:11:57.301 * Server initialized

1:M 31 Oct 2024 15:11:57.302 * Reading RDB base file on AOF loading...

1:M 31 Oct 2024 15:11:57.302 * Loading RDB produced by version 7.2.3

1:M 31 Oct 2024 15:11:57.302 * RDB age 9806 seconds

1:M 31 Oct 2024 15:11:57.302 * RDB memory usage when created 0.83 Mb

1:M 31 Oct 2024 15:11:57.302 * RDB is base AOF

1:M 31 Oct 2024 15:11:57.302 * Done loading RDB, keys loaded: 0, keys expired: 0.

1:M 31 Oct 2024 15:11:57.302 * DB loaded from base file appendonly.aof.1.base.rdb: 0.001 seconds

1:M 31 Oct 2024 15:11:57.302 * DB loaded from append only file: 0.001 seconds

1:M 31 Oct 2024 15:11:57.302 * Opening AOF incr file appendonly.aof.1.incr.aof on server start

1:M 31 Oct 2024 15:11:57.302 * Ready to accept connections tcp
```

**Comment by bo0tzz** [comment]
What REDIS_HOSTNAME is the immich server pod getting? And does that match the redis service's name?

**Comment by savisaar2** [comment]
It looks like the service is:

my-immich-redis-master

And that is what is set when the deployment loads.

**Comment by savisaar2** [comment]
I just noticed redis is being deployed into another node with a different label from what I have defined in my deployment. 

Why would that be?

**Comment by bo0tzz** [comment]
Aha. Your global nodeselector in the values only applies to deployments handled by the app-template chart we build on. But redis is a separate subchart (from bitnami) and so it doesn't apply to that.

**Comment by savisaar2** [comment]
So what would be the work around to specify a new separate deployment for
the redis and link them together using the Redis_hostbame env?

**Comment by savisaar2** [comment]
Okay it looks like I managed to get it up and and running by adding this under redis:

master.nodeSelector

Cheers for your help 😊

**Comment by savisaar2** [comment]
Just tagging onto this for advice, what's the best way to import my existing (previous immich instance assets) into the current instance? Currently it is setup brand new with empty gallery.
